// The Emscripten glue file (src/wasm-build/mqsim.mjs) is generated by
// engine/build-wasm.sh and gitignored, so there's no way to put a proper
// .d.ts alongside it. This is a deliberately loose ambient declaration -
// see src/hooks/useMqsimEngine.ts for the actual typed wrapper around what
// this module's default export resolves to.
declare module '*.mjs' {
  const createModule: (options?: Record<string, unknown>) => Promise<MqsimModule>;
  export default createModule;
}

// Shape of the object createMQSimModule() resolves to - the embind
// bindings exported from engine/mqsim/src/wasm/bindings.cpp. LPA/PPA come
// back as BigInt (64-bit types via embind), not number.
interface MqsimBlockAddress {
  channel: number;
  chip: number;
  die: number;
  plane: number;
  block: number;
  page: number;
}

interface MqsimMappingRow {
  lpa: bigint;
  ppa: bigint | null;
  mapped: boolean;
  address: MqsimBlockAddress | null;
}

interface MqsimState {
  mapping: MqsimMappingRow[];
}

interface MqsimEvent {
  type: string;
  streamId?: number;
  lpa?: bigint;
  ppa?: bigint;
  isWrite?: boolean;
  block?: {
    channel: number;
    chip: number;
    die: number;
    plane: number;
    block: number;
    page?: number;
  };
  eraseCount?: number;
  forMappingData?: boolean;
  dynamicWlConsidered?: boolean;
}

interface MqsimModule {
  init(ssdConfigXml: string, workloadXml: string): void;
  configure(ssdConfigXml: string, workloadXml: string): void;
  step(): boolean;
  run(n: number): boolean;
  getState(): MqsimState;
  setEventCallback(callback: ((event: MqsimEvent) => void) | null): void;
}
